trigger:
  - main

pool:
  name: "LabSelfHosted"

variables:
  buildConfiguration: "Release"
  libraryProject: "**/StringExtensions.csproj"
  testProject: "**/StringTesterApp.csproj"
  nugetFeedName: "Lab4-CICD-301283759-KetaPatel/StringUtilitiesFeed"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET 8 SDK"
    inputs:
      packageType: "sdk"
      version: "8.0.x"
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: "Restore NuGet packages - Library"
    inputs:
      command: "restore"
      projects: "$(libraryProject)"
      feedsToUse: "select"

  - task: DotNetCoreCLI@2
    displayName: "Build library project"
    inputs:
      command: "build"
      projects: "$(libraryProject)"
      arguments: "--configuration $(buildConfiguration) --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "Create NuGet package"
    inputs:
      command: "pack"
      packagesToPack: "$(libraryProject)"
      configuration: "$(buildConfiguration)"
      packDirectory: "$(Build.ArtifactStagingDirectory)"
      versioningScheme: "off"
      nobuild: true

  - task: NuGetAuthenticate@1
    displayName: "NuGet Authenticate"

  - task: NuGetCommand@2
    displayName: "Push package to Azure Artifacts"
    inputs:
      command: "push"
      packagesToPush: "$(Build.ArtifactStagingDirectory)/**/*.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "$(nugetFeedName)"
      allowPackageConflicts: true

  # Verify the package works by building and running the test app
  - task: DotNetCoreCLI@2
    displayName: "Restore NuGet packages - Test App"
    inputs:
      command: "restore"
      projects: "$(testProject)"
      feedsToUse: "select"
      vstsFeed: "$(nugetFeedName)"

  - task: DotNetCoreCLI@2
    displayName: "Build test app"
    inputs:
      command: "build"
      projects: "$(testProject)"
      arguments: "--configuration $(buildConfiguration) --no-restore"

  - task: PublishPipelineArtifact@1
    displayName: "Publish Artifacts"
    inputs:
      targetPath: "$(Build.ArtifactStagingDirectory)"
      artifact: "NuGetPackages"
      publishLocation: "pipeline"
